version: '3.5'


volumes:
  minio-data:
    driver: local
  data: {}

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: audit-service
    networks:
      - taskmanager_ntwrk
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - taskmanager_ntwrk
  db:
    build: postgresql
    image: taskmanager_postgresql:1.1.21
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - taskmanager_ntwrk
  pgadmin:
    build: pgadmin
    image: taskmanager_pgadmin:1.0.1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"
    networks:
      - taskmanager_ntwrk
  eureka-server:
    build: eureka-server
    image: taskmanager_eureka-server:1.0.9
    ports:
      - "8761:8761"
    networks:
      - taskmanager_ntwrk
  swagger-ui:
    build: swagger-ui
    image: taskmanager_swagger-ui:1.0.3
    ports:
      - "81:8080"
    networks:
      - taskmanager_ntwrk
  minio:
    build: minio
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioservice_user
      - MINIO_ROOT_PASSWORD=minioservice_pass
    command: server ~/minio --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - taskmanager_ntwrk
    volumes:
      - minio-data:/minio
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - taskmanager_ntwrk
  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - taskmanager_ntwrk
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9002:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
    networks:
      - taskmanager_ntwrk
  user-service:
    build: user-service
    image: taskmanager_user-service:1.1.38
    networks:
      - taskmanager_ntwrk
  audit-service:
    build: audit-service
    image: taskmanager_audit-service:1.1.10
    networks:
      - taskmanager_ntwrk
  task-service:
    build: task-service
    image: taskmanager_task-service:1.0.31
    networks:
      - taskmanager_ntwrk
  report-service:
    build: report-service
    image: taskmanager_report-service:1.2.35
    networks:
      - taskmanager_ntwrk
  gateway-service:
    build: gateway-service
    image: taskmanager_gateway-service:1.0.30
    ports:
      - "80:80"
    networks:
      - taskmanager_ntwrk
networks:
    taskmanager_ntwrk:
      name: taskmanager_ntwrk

