version: '3.5'
services:
  db:
    build: postgresql
    image: taskmanager_postgresql:1.0.40
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - taskmanager_ntwrk
  pgadmin:
    build: pgadmin
    image: taskmanager_pgadmin:1.0.1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"
    networks:
      - taskmanager_ntwrk
  eureka-server:
    build: eureka-server
    image: taskmanager_eureka-server:1.0.7
    ports:
      - "8761:8761"
    networks:
      - taskmanager_ntwrk
  swagger-ui:
    build: swagger-ui
    image: taskmanager_swagger-ui:1.0.3
    ports:
      - "81:8080"
    networks:
      - taskmanager_ntwrk
  user-service:
    build: user-service
    image: taskmanager_user-service:1.1.1
    networks:
      - taskmanager_ntwrk
  audit-service:
    build: audit-service
    image: taskmanager_audit-service:1.0.7
    networks:
      - taskmanager_ntwrk
  task-service:
    build: task-service
    image: taskmanager_task-service:1.0.4
    networks:
      - taskmanager_ntwrk
  gateway-service:
    build: gateway-service
    image: taskmanager_gateway-service:1.0.12
    ports:
      - "80:80"
    networks:
      - taskmanager_ntwrk
networks:
    taskmanager_ntwrk:
      name: taskmanager_ntwrk

