spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/report_service?ApplicationName=report-service-app

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.default_schema: report_app
      hibernate:
        show_sql: true
    open-in-view: true
  application:
    name: report

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

  instance:
    preferIpAddress: true

minio:
  bucket: reports
  url: http://localhost:9000
  accessKey: minioservice
  secretKey: minioservice