spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/audit_service?ApplicationName=audit-service-app
    username: postgres123
    password: postgres123

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.default_schema: audit_app
      hibernate:
        show_sql: true
    open-in-view: true


server:
  port: 80
