spring:
  data:
    mongodb:
      database: audit-service
      port: 27017
      host: localhost
      uri: mongodb://localhost:27017/audit-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group-1

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

  instance:
    preferIpAddress: true