spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/audit_service?ApplicationName=audit-service-app
    username: auditservice
    password: auditservice

  mvc:
    throw-exception-if-no-handler-found: false

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: audit_app
      hibernate:
        show_sql: true
    open-in-view: true

