spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/audit_service?ApplicationName=audit-service-app
    username: postgres123
    password: postgres123

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: audit_app
      hibernate:
        show_sql: true
    open-in-view: true
  application:
    name: audit

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

  instance:
    preferIpAddress: true