spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/audit_service?ApplicationName=audit-service-app
    username: auditservice
    password: auditservice

  mvc:
    throw-exception-if-no-handler-found: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: audit_app
      hibernate:
        show_sql: true
    open-in-view: true

  application:
    name: audit


jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: ITAcademy


server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
  instance:
    preferIpAddress: true