spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: audit-service
      port: 27017
      host: mongo

  application:
    name: audit


jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: ITAcademy


server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
  instance:
    preferIpAddress: true