server:
  port: 80

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users
          uri: lb://USERS/
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
        - id: task
          uri: lb://TASK/
          predicates:
            - Path=/api/v1/task/**
          filters:
            - StripPrefix=2
        - id: project
          uri: lb://TASK/
          predicates:
            - Path=/api/v1/project/**
          filters:
            - StripPrefix=2
        - id: audit
          uri: lb://AUDIT/
          predicates:
            - Path=/api/v1/audit/**
          filters:
            - StripPrefix=2
        - id: report
          uri: lb://REPORT/
          predicates:
            - Path=/api/v1/report/**
          filters:
            - StripPrefix=2

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka # адрес сервера обнаружения сервисов Eureka

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka # адрес сервера обнаружения сервисов Eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"

