spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/user_service?ApplicationName=user-service-app

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: user_app
      hibernate:
        show_sql: true
    open-in-view: true
  application:
    name: users
#  mail:
#    host: localhost
#    port: 1025
#    username: hello
#    password: hello
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000


  mail:
    host: smtp.mail.ru
    port: 465
    username: l2mypers03@mail.ru
    password: "6jaRa5gdhCHN1jamhaSD"
    properties:
      "mail.smtp.ssl.enable": true
      mail:
        encoding: UTF-8
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true



server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

  instance:
    preferIpAddress: true





