spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/user_service?ApplicationName=user-service-app
    username: userservice
    password: userservice

  mvc:
    throw-exception-if-no-handler-found: false

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: user_app
      hibernate:
        show_sql: true
    open-in-view: true

  application:
    name: users

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
#  mail:
#    host: smtp.mail.ru
#    port: 465
#    username: l2mypers03@mail.ru
#    password: "6jaRa5gdhC7HN1j7amha7SD"
#    properties:
#      "mail.smtp.ssl.enable": true
#      mail:
#        encoding: UTF-8
#        transport:
#          protocol: smtp
#        smtp:
#          auth: true
#          starttls:
#            enable: true

jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: ITAcademy

mail-set:
  url: "http://localhost/api/v1/users/verification"
  mailfrom: l2mypers03@mail.ru
  htmlform: verification.html
  subject: "TaskManager - letter confirmation"

