spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/user_service?ApplicationName=user-service-app
    username: userservice
    password: userservice

  mvc:
    throw-exception-if-no-handler-found: false

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: user_app
      hibernate:
        show_sql: true
    open-in-view: true
  kafka:
    bootstrap-servers: kafka:9092

  application:
    name: users

  mail:
    host: smtp.mail.ru
    port: 465
    username: l2mypers03@mail.ru
    password: "6jaRa5gdhCHN1jamhaSD"
    properties:
      "mail.smtp.ssl.enable": true
      mail:
        encoding: UTF-8
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: ITAcademy
  systemToken: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiU1lTVEVNIiwibWFpbCI6InN5c3RlbUBzeXN0ZW0uYnkiLCJ1dWlkIjoiYTg3NTIzY2YtYzYzYS00YTNlLWI3YzItZTI5NzQyNjkyZTFmIiwiZmlvIjoic3lzdGVtIiwiaXNzIjoiSVRBY2FkZW15IiwiaWF0IjoxNjkyMDM2MjQ0LCJleHAiOjI1NTU1NTU1NTV9.vbmL9zulS45tUbecO3H0AN5N8FI0R545VrvpcdyJ0JU"

mail-set:
  url: "http://localhost/api/v1/users/verification"
  mailfrom: l2mypers03@mail.ru
  htmlform: verification.html
  subject: "TaskManager - letter confirmation"

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
  instance:
    preferIpAddress: true