spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/user_service?ApplicationName=user-service-app
    username: postgres123
    password: postgres123

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.default_schema: user_app
      hibernate:
        show_sql: true
    open-in-view: true
    database: postgresql
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 80
  error: #  verifity test
    include-message: always
    include-binding-errors: always






  #<!-- value="jdbc:postgresql://pg_db:5432/crm_db"/>-->
