spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/user_service?ApplicationName=user-service-app
    username: userservice
    password: userservice
  #    url: jdbc:postgresql://localhost:5432/user_service?ApplicationName=user-service-app
  #    username: postgres123
  #    password: postgres123

  mvc:
    throw-exception-if-no-handler-found: false

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: user_app
      hibernate:
        show_sql: true
    open-in-view: true


#server:
#  port: 80

