spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/task_service?ApplicationName=task-service-app
    username: taskservice
    password: taskservice

  mvc:
    throw-exception-if-no-handler-found: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: task_app
      hibernate:
        show_sql: true
    open-in-view: true

jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: ITAcademy