spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/task_service?ApplicationName=task-service-app

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: task_app
      hibernate:
        show_sql: true
    open-in-view: true
  application:
    name: task

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

  instance:
    preferIpAddress: true